### ISSUE TITLE
[BUG] LoadBalancer service is stuck in pending state

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/m-aws-kubernetes-service#38]
**Describe the bug**
During tesing of istio module I was unable to get istio gateway working due to LB problem https://github.com/epiphany-platform/epiphany/issues/1910#issuecomment-759543468. AWS is unable to create LB due to missing subnet.

**How to reproduce**
1. deploy latest develop of awsbi with default config
2. deploy latest develop of awsks with default config
3. create LoadBalancer service with external IP enabled

**Expected behavior**
LB should get public IP address.

**Config files**
```yaml
kind: awsbi-config
awsbi:
  name: istio-mop
  instance_count: 0
  region: eu-west-1
  use_public_ip: false
  nat_gateway_count: 1
  subnets:
    private:
      count: 1
    public:
      count: 1
  rsa_pub_path: /shared/vms_rsa.pub
  os: redhat
```
```yaml
kind: awsks-config
awsks:
  name: istio-mop
  vpc_id: vpc-01b5b135bd2af9246
  region: eu-west-1
  subnet_ids: null
  private_route_table_id: rtb-03cf619cf77780d05
  disk_size: 32
  autoscaler_scale_down_utilization_threshold: 0.65
  ami_type: AL2_x86_64
  ec2_ssh_key: null
  worker_groups:
    - name: default_wg
      instance_type: t2.medium
      asg_desired_capacity: 1
      asg_min_size: 1
      asg_max_size: 1
```

**Environment**
- Cloud provider: AWS

**Additional context**
N/A
